name: 部署文档

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      - master

jobs:
  deploy-gh-pages:
    name: Deploy Gh Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set Node Version
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Building
        env:
          NODE_OPTIONS: --max_old_space_size=8000
        run: pnpm run build

      # - name: Delete gh-pages branch
      #   run: |
      #     git fetch origin
      #     git push origin --delete gh-pages || true  # 忽略错误，若分支不存在

      - name: Deploy Dist
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: gh-pages
          folder: dist
          clean: true
          force: true
